### ISSUE TITLE
El sketch y el mockup/wireframe deben estar en carpetas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#1]
No es buena práctica dejar los archivos de diseño en la carpeta raíz. 

La estructura del proyecto debe ser adecuada (crear una carpeta para las imágenes, otra para los sketch/mockups). Es importante que contenga SKETCH y MOCKUP/Wireframe (debe estar en formato: PDF, PNG o JPG).

**Comment by Saimonher2002** [comment]
realizado
