### ISSUE TITLE
Detalles de la documentación a corregir

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#15]
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L5-L7
El único parámetro que tenes es el evento. Es decir:
`* @param {Event} e - Objeto de evento del evento que desencadenó la función.` 

El otro @param y el @return no deberías ponerlos.

No es necesario el return en los siguientes casos:
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L24

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L68

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L91

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L137

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L167

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L184

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L209

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L235

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L246

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L268

Debería ser **@method**. No es necesario el @param y el @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L299-L301

Debería ser **@method**. No es necesario el @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L339

Falto documentar el 
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L357

Debería ser **@method**. No es necesario el @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L377

Debería ser **@method**. No es necesario el @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/carrito.js#L403

**Comment by Saimonher2002** [comment]
Realizado
