### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#16]
Falta documentar:
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/compra.js#L10

Debería ser @method. No es necesario el @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/compra.js#L19-L21

**Comment by Saimonher2002** [comment]
Completado
