### ISSUE TITLE
Documentación en pedido

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#18]
Debería ser @method. No debería tener un @return ni @param
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/pedido.js#L15-L18

**Comment by Saimonher2002** [comment]
Completado
