### ISSUE TITLE
Documentación en script

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#19]
Debería ser @method. No debería llevar @param y @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/scripts.js#L8-L10

No debería llevar @param y @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/main/assets/js/scripts.js#L26-L27

No debería llevar @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/main/assets/js/scripts.js#L67

Debería ser @method
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/scripts.js#L108

Debería ser @method
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/scripts.js#L133

Debería ser @method. No debería ir el @return
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/0d24f13ca7e0b09c1c84fecbb28c9a120a63bc10/assets/js/scripts.js#L257-L259

**Comment by Saimonher2002** [comment]
Completado
