### ISSUE TITLE
La indentación no es correcta en todos los archivos

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#2]
Revisar:

- carrito.html
- contacto.html
- nosotros.html
- productos.html

(desde webstorm pueden seleccionar el contenido de todo el archivo, y presionando Ctrol+Alt+i el codigo debe indentarse. Sino, desde el menu Code > Auto-Indent Lines)

**Comment by Saimonher2002** [comment]
realizado
