### ISSUE TITLE
Falta atributo alt en algunas imágenes

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#3]
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/index.html#L54

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/index.html#L58

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/index.html#L62

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/index.html#L75

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L61

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L69

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L76

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L83

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L91

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L98

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L105

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L114

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L121

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/productos.html#L128

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/nosotros.html#L53

**Comment by Saimonher2002** [comment]
realizado
