### ISSUE TITLE
Error en etiqueta meta

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#5]
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/index.html#L5-L6

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/carrito.html#L5-L6

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/71bfa0c6456bb83a92de223bf7d88805739d7987/contacto.html#L6-L7

La forma correcta de emplear la etiqueta meta es:
`<meta name="autor" content="Simon Hernandez y Tiziano Marabotto"`

También verificar que falta el **name="descripcion"**

**Comment by Saimonher2002** [comment]
realizado

**Comment by edme88** [comment]
Verificar que falta el name="descripcion"
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/ae2743020a573c85b151d238418838bd11eb3477/carrito.html#L6

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/ae2743020a573c85b151d238418838bd11eb3477/contacto.html#L7

**Comment by edme88** [comment]
Verificar que falta el name="descripcion"
https://ucc-labcompu2.github.io/filminas/U4_HTML.html#/6

**Comment by tizx** [comment]
solucionado
