### ISSUE TITLE
Falta etiqueta caption dentro de la tabla

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-hernandez-marabotto#8]
Falta la etiqueta `<caption>` dentro de la tabla.

**Comment by Saimonher2002** [comment]
realizado

**Comment by edme88** [comment]
Según lo visto en clase, y documentación de la W3school https://www.w3schools.com/tags/tag_caption.asp , la etiqueta caption debe ir dentro de la etiqueta table.

Revisar:
https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/ae2743020a573c85b151d238418838bd11eb3477/carrito.html#L66-L100

https://github.com/UCC-LabCompu2/proyecto2022-hernandez-marabotto/blob/ae2743020a573c85b151d238418838bd11eb3477/productos.html#L42-L52
